name: langgraph-langsmith-google
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - jupyterlab
  - ipywidgets
  - langgraph
  - langsmith
  - langchain-google-genai
  - langchain-community
  - tavily-python